FROM aivision-backend:latest

USER root

# 复制本地构建好的 JAR 文件替换原有的
COPY backEnd/api_gateway/target/api-gateway-0.0.1-SNAPSHOT.jar /app/app.jar

# 确保权限正确
RUN chown appuser:appuser /app/app.jar

USER appuser
